name: Deploy Site 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - run: |
          pip install -r requirements.txt
          make clean
          make deploy
          mkdocs gh-deploy --force
