name: Deploy Site 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.2

      - name: Build and deploy
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          pip install -r requirements.txt
          make clean
          make deploy
          mkdocs gh-deploy --force
